### PR TITLE
fix: support localhost urls

### LINKED ISSUE #801: Bug: unable to use localhost as URL
Hi everyone!

I'm unable to use localhost as URL in autocannon-ui:
image

The same URL in CLI works perfectly:
image

I think that the problem lies here:
https://github.com/nearform/autocannon-ui/blob/master/packages/autocannon-ui-backend/routes/execute.js#L7

### PR DESCRIPTION
**Pull request by simoneb**
Fixes #801

### CODE REVIEW

File: packages/autocannon-ui-backend/routes/execute.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import execute from '../services/autocannon.js'
 
 const schema = {
   body: S.object()
-    .prop('url', S.string().format('url').required())
+    .prop('url', S.string().format('uri').required())
```
Comment (simoneb) [inline packages/autocannon-ui-backend/routes/execute.js:7]: the url format is deprecated, see https://ajv.js.org/guide/formats.html

**Review by LiSmi — APPROVED** [review]

**Review by jdarling — COMMENTED** [review]
LGTM
